services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    container_name: api
    build:
      context: .
      dockerfile: ConferenceAttendees.Api/Dockerfile
    ports:
       - "7203:7203"
    depends_on: [conferenceattendees.database, conferenceattendees.seq_logs]
    networks:
      - app-network

  conferenceattendees.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-db
    hostname: mssql
    environment: 
      - MSSQL_SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1414:1433"
    networks:
      - app-network

  conferenceattendees.seq_logs:
    image: datalust/seq
    container_name: seq_logs
    restart: unless-stopped
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  